syntax = "proto3";

package gophkeeper.v1;

option go_package = "github.com/Irongoshan-ux/gophkeeper/pkg/gophkeeper/v1;gophkeeperv1";

import "google/protobuf/timestamp.proto";

service SecretService {
  rpc CreateSecret (CreateSecretRequest) returns (Secret);
  rpc GetSecret (GetSecretRequest) returns (Secret);
  rpc ListSecrets (ListSecretsRequest) returns (ListSecretsResponse);
  rpc UpdateSecret (UpdateSecretRequest) returns (Secret);
  rpc DeleteSecret (DeleteSecretRequest) returns (DeleteSecretResponse);
  rpc Sync (SyncRequest) returns (SyncResponse);
}

enum SecretType {
  SECRET_TYPE_UNSPECIFIED = 0;
  SECRET_TYPE_CREDENTIALS = 1;
  SECRET_TYPE_TEXT = 2;
  SECRET_TYPE_BINARY = 3;
  SECRET_TYPE_CARD = 4;
  SECRET_TYPE_OTP = 5;
}

message Secret {
  string id = 1;
  SecretType type = 2;
  string name = 3;
  bytes encrypted_data = 4;
  int64 version = 5;
  google.protobuf.Timestamp updated_at = 6;
  bool deleted = 7;
}

message CreateSecretRequest {
  SecretType type = 1;
  string name = 2;
  bytes encrypted_data = 3;
}

message GetSecretRequest {
  string id = 1;
}

message ListSecretsRequest {}

message ListSecretsResponse {
  repeated Secret secrets = 1;
}

message UpdateSecretRequest {
  string id = 1;
  SecretType type = 2;
  string name = 3;
  bytes encrypted_data = 4;
  int64 version = 5;
}

message DeleteSecretRequest {
  string id = 1;
  int64 version = 2;
}

message DeleteSecretResponse {
  string id = 1;
  int64 version = 2;
}

message SyncRequest {
  google.protobuf.Timestamp since = 1;
}

message SyncResponse {
  repeated Secret secrets = 1;
}
