// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Secret struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Type          int16
	Name          string
	EncryptedData []byte
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Login        string
	PasswordHash string
	CreatedAt    time.Time
}
