// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	ListSecrets(ctx context.Context, userID pgtype.UUID) ([]Secret, error)
	ListSecretsSince(ctx context.Context, arg ListSecretsSinceParams) ([]Secret, error)
	SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (Secret, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
}

var _ Querier = (*Queries)(nil)
