// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (user_id, type, name, encrypted_data, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at
`

type CreateSecretParams struct {
	UserID        pgtype.UUID
	Type          int16
	Name          string
	EncryptedData []byte
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.EncryptedData,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.EncryptedData,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at FROM secrets
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetSecretParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, arg.ID, arg.UserID)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.EncryptedData,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at FROM secrets
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSecrets(ctx context.Context, userID pgtype.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.EncryptedData,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsSince = `-- name: ListSecretsSince :many
SELECT id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at FROM secrets
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type ListSecretsSinceParams struct {
	UserID    pgtype.UUID
	UpdatedAt time.Time
}

func (q *Queries) ListSecretsSince(ctx context.Context, arg ListSecretsSinceParams) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecretsSince, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.EncryptedData,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSecret = `-- name: SoftDeleteSecret :one
UPDATE secrets
SET deleted_at = $3, updated_at = $3, version = $4
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at
`

type SoftDeleteSecretParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	DeletedAt pgtype.Timestamptz
	Version   int64
}

func (q *Queries) SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, softDeleteSecret,
		arg.ID,
		arg.UserID,
		arg.DeletedAt,
		arg.Version,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.EncryptedData,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET name = $3, encrypted_data = $4, type = $5, version = $6, updated_at = $7
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, type, name, encrypted_data, version, created_at, updated_at, deleted_at
`

type UpdateSecretParams struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	EncryptedData []byte
	Type          int16
	Version       int64
	UpdatedAt     time.Time
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.EncryptedData,
		arg.Type,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.EncryptedData,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
